import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/componenentes/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Primeiro Projeto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
